name: Deploy to Ubuntu Server

on:
  release:
    types: [ published ] # Triggers when a new release is published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t fsdmitclub:latest .

      - name: Save Docker image to file
        run: docker save fsdmitclub:latest -o fsdmitclub-latest.tar

      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "fsdmitclub-latest.tar"
          target: "~/"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop fsdmitclub-container || true
            sudo docker rm fsdmitclub-container || true
            sudo docker rmi -f fsdmitclub:latest || true
            sudo docker load -i ~/fsdmitclub-latest.tar
            sudo docker run -d --name fsdmitclub-container -p 80:80 -e DB_URL="${{ secrets.DB_URL }}" -e DB_USERNAME="${{ secrets.DB_USERNAME }}" -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" -e MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}" -e MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" -e MAIL_HOST="${{ secrets.MAIL_HOST }}" -e MAIL_PORT="${{ secrets.MAIL_PORT }}" fsdmitclub:latest