name: Deploy to Ubuntu Server

on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t fsdmitclub:latest .

    - name: Save Docker image to file
      run: docker save fsdmitclub:latest -o fsdmitclub-latest.tar

    - name: Copy Docker image to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "fsdmitclub-latest.tar"
        target: "~/"

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker load -i ~/fsdmitclub-latest.tar
          sudo docker stop fsdmitclub-container || true
          sudo docker rm fsdmitclub-container || true
          sudo docker run -d --name fsdmitclub-container -p 80:80 fsdmitclub:latest