name: Check for Trailing Spaces

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  check-code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Checkstyle
        run: |
          curl -LJO https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.8.0/checkstyle-10.8.0-all.jar

      - name: Run Checkstyle with custom rules
        run: |
          java -jar checkstyle-10.8.0-all.jar -c checks/checkstyle.xml src/